package com.bigdata.chunks.bean;


// Generated Jun 21, 2012 4:19:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthMaster generated by hbm2java
 */
public class ArticleMaster implements java.io.Serializable {

	
	
	private Integer articleId;
	private String articleName;
	private String articleDesc;
	
	private String isActive;
	private String modifiedDate;
	private String createdDate;
	
	private Integer categoryId;
	private String isFeature;
	private String articleLocation;
	private String status;
	private String articleTitle;

	public ArticleMaster() {
	}

	public ArticleMaster(String articleName, String articleDesc, 
					String isActive, String modifiedDate, String createdDate,
			Integer categoryId, String isFeature, String articleLocation, String status, String articleTitle) {
		this.articleName = articleName;
		this.articleDesc = articleDesc;
		this.articleDesc = articleDesc;
		
		this.isActive = isActive;
		this.modifiedDate = modifiedDate;
		this.createdDate = createdDate;
		
		this.categoryId = categoryId;
		this.isFeature = isFeature;
		
		this.articleLocation = articleLocation;
		this.status = status;
		this.articleTitle = articleTitle;
		
		
	}

	public Integer getArticleId() {
		return articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public String getArticleName() {
		return articleName;
	}

	public void setArticleName(String articleName) {
		this.articleName = articleName;
	}

	public String getArticleDesc() {
		return articleDesc;
	}

	public void setArticleDesc(String articleDesc) {
		this.articleDesc = articleDesc;
	}

	public String getIsActive() {
		return isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public String getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(String modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getIsFeature() {
		return isFeature;
	}

	public void setIsFeature(String isFeature) {
		this.isFeature = isFeature;
	}

	public String getArticleLocation() {
		return articleLocation;
	}

	public void setArticleLocation(String articleLocation) {
		this.articleLocation = articleLocation;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getArticleTitle() {
		return articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}



}
