package com.bigdata.chunks.bean;


// Generated Jun 21, 2012 4:19:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthMaster generated by hbm2java
 */
public class RecoverMaster implements java.io.Serializable {

	
	private static final long serialVersionUID = -4861811887352080966L;
	
	private Integer recoverId;
	private Integer userId;
	
	private String securityQuestion;
	private String securityAnswer;

	private String modifiedDate;
	private String createdDate;

	

	public RecoverMaster() {
	}

	public RecoverMaster(String securityQuestion, String securityAnswer, 
			String modifiedDate, String createdDate,
			Integer userId) {
		
		this.securityQuestion = securityQuestion;
		this.securityAnswer = securityAnswer;
		
		this.modifiedDate = modifiedDate;
		this.createdDate = createdDate;
		
		this.userId = userId;



	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRecoverId() {
		return recoverId;
	}

	public void setRecoverId(Integer recoverId) {
		this.recoverId = recoverId;
	}

	public String getSecurityQuestion() {
		return securityQuestion;
	}

	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	public String getSecurityAnswer() {
		return securityAnswer;
	}

	public void setSecurityAnswer(String securityAnswer) {
		this.securityAnswer = securityAnswer;
	}

	public String getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(String modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}



}
