package com.bigdata.chunks.bean;

// Generated Aug 13, 2012 7:55:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	
	private static final long serialVersionUID = 4201735818254881086L;
	
	private Long userId;
	private String userName;
	private String userPassword;
	private String userGender;
	private String userCountry;
	private String userAboutYou;

	public User() {
	}

	public User(String userName, String userPassword, String userGender,
			String userCountry, String userAboutYou) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userGender = userGender;
		this.userCountry = userCountry;
		this.userAboutYou = userAboutYou;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserGender() {
		return this.userGender;
	}

	public void setUserGender(String userGender) {
		this.userGender = userGender;
	}

	public String getUserCountry() {
		return this.userCountry;
	}

	public void setUserCountry(String userCountry) {
		this.userCountry = userCountry;
	}

	public String getUserAboutYou() {
		return this.userAboutYou;
	}

	public void setUserAboutYou(String userAboutYou) {
		this.userAboutYou = userAboutYou;
	}

}
