package com.synechron.prm.bean;


// Generated Jun 21, 2012 4:19:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuthMaster generated by hbm2java
 */
public class AuthMaster implements java.io.Serializable {

	
	private static final long serialVersionUID = -4861811887352080966L;
	
	private Integer userId;
	private String userName;
	private String password;
	private String firstName;
	private String lastName;
	private String email;
	private String mobile;
	private String isAdmin;
	private String isActive;
	private String modifiedDate;
	private String createdDate;
	
	private String address;
	private String gender;
	private String city;
	private String state;
	private String country;
	private String aboutUser;
	

	public AuthMaster() {
	}

	public AuthMaster(String userName, String password, String firstName,
			String lastName, String email, String mobile, String isAdmin,
			String isActive, String modifiedDate, String createdDate,
			String address, String gender, String city, String state,
			String country, String aboutUser) {
		this.userName = userName;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.mobile = mobile;
		this.isAdmin = isAdmin;
		this.isActive = isActive;
		this.modifiedDate = modifiedDate;
		this.createdDate = createdDate;
		
		this.address = address;
		this.gender = gender;
		this.city = city;
		this.state = state;
		this.country = country;
		this.aboutUser = aboutUser;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public String getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(String modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getAboutUser() {
		return aboutUser;
	}

	public void setAboutUser(String aboutUser) {
		this.aboutUser = aboutUser;
	}

}
